# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter/proto/Example.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='greeter/proto/Example.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bgreeter/proto/Example.proto\x12\x07\x65xample\"\x1e\n\x0eGreeterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x0fGreeterResponse\x12\x10\n\x08greeting\x18\x01 \x01(\tb\x06proto3')
)




_GREETERREQUEST = _descriptor.Descriptor(
  name='GreeterRequest',
  full_name='example.GreeterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.GreeterRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=70,
)


_GREETERRESPONSE = _descriptor.Descriptor(
  name='GreeterResponse',
  full_name='example.GreeterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='example.GreeterResponse.greeting', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['GreeterRequest'] = _GREETERREQUEST
DESCRIPTOR.message_types_by_name['GreeterResponse'] = _GREETERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GreeterRequest = _reflection.GeneratedProtocolMessageType('GreeterRequest', (_message.Message,), dict(
  DESCRIPTOR = _GREETERREQUEST,
  __module__ = 'greeter.proto.Example_pb2'
  # @@protoc_insertion_point(class_scope:example.GreeterRequest)
  ))
_sym_db.RegisterMessage(GreeterRequest)

GreeterResponse = _reflection.GeneratedProtocolMessageType('GreeterResponse', (_message.Message,), dict(
  DESCRIPTOR = _GREETERRESPONSE,
  __module__ = 'greeter.proto.Example_pb2'
  # @@protoc_insertion_point(class_scope:example.GreeterResponse)
  ))
_sym_db.RegisterMessage(GreeterResponse)


# @@protoc_insertion_point(module_scope)
